export const b1 = [
    {
        id  : 1 ,
        category : "women",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/t/a/h/s-vkur1292-varanga-original-imagsaph3vszdfux.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/5/z/c/xxl-vkur1324-varanga-original-imagrhtuecutgyhz.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/kqpj4i80/kurta/j/h/8/xl-ku632lgn-mokshi-original-imag4nmvvfny6vyf.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/5/c/o/m-febb-372-377-ethnicbasket-original-imagxffgqn7mgbef.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/k6wiefk0/kurta/z/z/k/l-303k111-saara-original-imafp9bxmkzzfkyp.jpeg?q=70",
        title : "Women's Stylish Clothing",
        price : "400",
        quantity : 0 
    },
    {
        id  : 2 ,
        category : "women",
        imgSrc1: "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/q/h/z/xxl-machh-01-lamba-creations-original-imagjgertsghwgn8.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/9/t/c/m-ku779grn-mokshi-original-imagm5wzqgthgaw8.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/z/b/q/xxl-psk103-glorious-original-imaftnbjjzfgxzej-bb.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/kyeqjrk0/dress/m/r/t/s-03-lamba-creations-original-imaganh2bczj5qvf.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/l52sivk0/shopsy-kurta/j/z/n/m-shopsy-t-530351-ethnic-basket-original-imagftu7ypcacdmg.jpeg?q=70",
        title : "Women's Stylish Clothing",
        price : "470",
        quantity : 0 
    },
    {
        id : 3 ,
        category : "men",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/3/z/h/s-sc24-csmawhd6020-campus-sutra-original-imahy7hhbycz4mcc.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/f/d/p/s-no-sc24-csmawjk016-campus-sutra-original-imahy7hddc3z9tww.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/w/u/z/-original-imagzc8xrheygnzp.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jacket/d/3/6/s-no-ss24-csm-aw-jk1119-campus-sutra-original-imagznhv2ezt4fty.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/t/q/e/m-sum24-csmawhd6017-campus-sutra-original-imagycsgbu9snqfz.jpeg?q=70",
        title : "Men's Stylish Clothing",
        price : "450",
        quantity : 0 
    },
    {
        id : 4 ,
        category : "men",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/s/k/7/-original-imagyz2cvbg3cymg.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/d/k/v/xl-sum24-csmawhd6169-campus-sutra-original-imagycsgdyps82kz.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/i/b/r/-original-imagzcbgbzsepxqa.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweater/y/f/i/-original-imagzcbgvdckbzeq.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/c/w/v/xl-aw24-csmawhd6170-campus-sutra-original-imagxvw6zhk8fkqh.jpeg?q=70",
        title : "Men's Stylish Clothing",
        price : "380",
        quantity : 0 
    },
    {
        id : 5 ,
        category : "kid",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/l/x/a/3-4-years-macnsut120-disney-by-miss-chief-original-imagzm982gy9fhag.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/k/w/u/5-6-years-hft-23hr3-on-pe-ics-hellcat-original-imagn9wcf7tzzx8p.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/c/i/o/9-10-years-hft-23hr3-pe-ics-br-hellcat-original-imagn9wcvmrpbjdz.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/v/t/a/13-14-years-hft-23hr3-mu-icj-pe-hellcat-original-imagn9wcy875upst.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/i/x/p/1-2-years-dsn-hfs-106-3-disney-by-miss-chief-original-imagwdzdxz4pceck.jpeg?q=70",
        title : "Kids's Stylish Clothing",
        price : "220",
        quantity : 0 
    },
    {
        id : 6 ,
        category : "kid",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/g/l/7/3-4-years-mactshrt148-disney-by-miss-chief-original-imagchtskjfyzapg-bb.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/p/q/o/1-2-years-mactshrt310-disney-by-miss-chief-original-imagzgmfz5sgjfds.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/i/b/p/4-5-years-mactshrt160-marvel-by-miss-chief-original-imag2mrqguhjhfqv-bb.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-apparel-combo/l/x/a/3-4-years-macnsut120-disney-by-miss-chief-original-imagzm982gy9fhag.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/kids-t-shirt/2/f/d/2-3-years-mactshrt332-disney-by-miss-chief-original-imagzzftrj49zky7.jpeg?q=70",
        title : "Kid's Stylish Clothing",
        price : "690",
        quantity : 0 
    },
    {
        id : 7 ,
        category : "electronics",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/w/e/q/-original-imagq425shghrgzz.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/q/q/-original-imagxp8tzzwyhkzr.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/b/z/y/-original-imagxp8tgyu9hjzk.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/5/a/d/-original-imagxp8udhcfyxhy.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/a/z/2/-original-imagsem7sww2dved.jpeg?q=70",
        title : "Stylish Watch",
        price : "1209",
        quantity : 0 
    },
    {
        id : 8 ,
        category : "electronics",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/projector/s/y/m/zeb-pixaplay-16-with-android-9-0-full-hd-1080p-dual-band-wifi-bt-original-imahyynappwznmrd.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/projector/a/k/a/zeb-pixaplay-15-18-37-zeb-pixaplay-15-led-projector-zebronics-original-imagxy7pfps2fjyz.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/kx50gi80/projector/r/9/p/zeb-pixa-play-12-5-6-dobly-audio-led-projector-zebronics-original-imag9z3yujqmzqt4.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/projector/r/s/i/zeb-pixaplay-18-19-zeb-pixaplay-18-full-hd-zebronics-original-imagmgtm4nh4eueu.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/kpvivm80/projector/h/i/m/zeb-lp4000-zeb-lp4000-zebronics-original-imag4ycmpcqn4ush.jpeg?q=70",
        title : "Electronic Smart Gadget ",
        price : "420",
        quantity : 0 
    },
    {
        id : 9 ,
        category : "jewellery",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/y/a/2/na-na-bol-choker-201-rofarword-original-imagg9t2mu4k3mu2.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/f/s/f/na-na-2-sat-set-101-rofarword-original-imagm92hbgu2f3eh.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/a/h/q/na-na-9599mlct-vatsalya-creation-original-imagk85qahhsxqm9.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/a/g/p/na-na-tika-set-104-rangrozo-jewellery-original-imaggtn9zhtwjp7w.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/jewellery-set/j/3/f/na-na-sat-set-101-rangrozo-jewellery-original-imagkydaphxquhs7.jpeg?q=70",
        title : "Necklace",
        price : "3276",
        quantity : 0 
    },
    {
        id : 10 ,
        category : "jewellery",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/pendant-locket/f/k/7/na-na-un-00-university-trendz-original-imagwdzy535axtym.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/pendant-locket/c/f/5/-original-imagqgcx3ckd7es6.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/jkcwakw0/pendant-locket/z/z/e/rnpc6043-rn-original-imaf7pwxehfearyw.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/pendant-locket/3/o/f/-original-imagqgcypqgqhhpf.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/l1xwqkw0/pendant-locket/g/x/n/-original-imagde4vvyvafxt8.jpeg?q=70",
        title : "Pendant",
        price : "770",
        quantity : 0 
    },
    {
        id : 11 ,
        category : "food",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/g/d/j/-original-imahycu8qs4jy8hc.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/k8ro3gw0/nut-dry-fruit/3/m/j/500-california-almonds-250g-each-pack-of-2-pouch-eighty7-original-imafqpmmjc9vv35g.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/y/d/4/500-popular-california-1-pouch-naturoz-original-imagj65uycjpax3z.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/e/m/o/250-premium-natural-californian-badam-almonds-1-mason-jar-nature-original-imagztxgutq3rnjy.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/e/o/x/500-popular-california-1-pouch-scorist-original-imagrng9krchkm7a.jpeg?q=70",
        title : "Dry Fruits",
        price : "398",
        quantity : 0
    },
    {
        id : 12 ,
        category : "food",
        imgSrc1 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/o/g/b/400-combo-pack-100-4-almond-cashew-pistachios-anjeer-figs-4-original-imagzq69megvccgh.jpeg?q=70",
        imgSrc2 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/x/8/t/1000-combo-pack-of-cashews-almonds-pistachios-walnuts-badam-original-imaghdttmzyhhnaz.jpeg?q=70",
        imgSrc3 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/s/y/c/750-dry-fruits-combo-pack-of-healthy-5-kaju-pista-badam-akhrot-original-imaghdtzbgmvhtqg.jpeg?q=70",
        imgSrc4 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/o/d/3/200-berry-mix-1-pouch-farmley-original-imagxe93hqcfwbmf.jpeg?q=70",
        imgSrc5 : "https://rukminim2.flixcart.com/image/612/612/xif0q/nut-dry-fruit/z/m/b/600-dry-fruits-combo-pack-of-pistachios-almonds-cashews-kaju-original-imagqq5kgjenmewd.jpeg?q=70",
        title : "Dry Fruits",
        price : "645",
        quantity : 0
    },
]